server:
  port: 80  # 项目端口

spring:
  datasource:
    url: jdbc:mysql://114.115.213.72:3306/axblog?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: axblog
  # Redis配置
  redis:
    host: 192.168.168.101
    port: 6379
    password: xsh981104
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

# 配置Mybatis-Plus
mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    # 例如：属性名映射 user_name --> userName
    # 例如：类名映射 address_book --> AddressBook
    map-underscore-to-camel-case: true
    # 开启MP运行日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0